apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-persistent-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /persistent_volume/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-persistent-volume-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logrotate-config
data:
  my_logs.conf: |
    /mnt/fastapi_app/*.log {
      rotate 3
      size 100k
      compress
      delaycompress
      dateformat -%Y%m%d_%H%M%S
      missingok
      notifempty
      copytruncate
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: logrotate-cronjob
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: logrotate
            image: docker.io/kicm/logrotate
            volumeMounts:
            - name: local-storage
              mountPath: /mnt/fastapi_app
            - name: logrotate-conf
              mountPath: /etc/logrotate.d
          volumes:
            - name: local-storage
              persistentVolumeClaim:
                claimName: local-persistent-volume-claim
            - name: logrotate-conf
              configMap:
                name: logrotate-config
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: archiver-cronjob
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: archiver
            image: archiver-image
            imagePullPolicy: Never
            volumeMounts:
              - name: local-storage
                mountPath: /mnt/fastapi_app
          restartPolicy: Never
          volumes:
            - name: local-storage
              persistentVolumeClaim:
                claimName: local-persistent-volume-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fastapi-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: local-storage
              mountPath: /mnt/fastapi_app
      volumes:
        - name: local-storage
          persistentVolumeClaim:
            claimName: local-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000